### ISSUE TITLE
Unexpected runtime error when applying vfy

### ISSUE THREAD

**Issue by fedorov** [afshinmessiah/PyDicomVerify#7]
When running vfy on the attached file, I get the following:

```shell
$ python shell_cmd_dcm_vfy.py -i prostate_sr.dcm
Traceback (most recent call last):
  File "/Users/af61/.pyenv/versions/pydicomverify3.8.2/lib/python3.8/site-packages/pydicom/tag.py", line 102, in Tag
    long_value = int(arg, 16)
ValueError: invalid literal for int() with base 16: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "shell_cmd_dcm_vfy.py", line 17, in <module>
    main(sys.argv[1:])
  File "shell_cmd_dcm_vfy.py", line 15, in main
    print(fx.verify_pyverify(args.input_file, '', args.verbose))
  File "/Users/af61/github/PyDicomVerify/local_fix_vfy.py", line 191, in verify_pyverify
    my_code_output = verify_dicom(file, verbose, '')
  File "/Users/af61/github/PyDicomVerify/rightdicom/dcmvfy/verify.py", line 40, in verify_dicom
    log = verify_dicom_dataset(ds, verbose, profile, fix_trivials)
  File "/Users/af61/github/PyDicomVerify/rightdicom/dcmvfy/verify.py", line 30, in verify_dicom_dataset
    SelectAndRunCompositeIOD(ds, verbose, log, profile, fix_trivials)
  File "/Users/af61/github/PyDicomVerify/rightdicom/dcmvfy/iodcomp_select_h.py", line 284, in SelectAndRunCompositeIOD
    iod = CompositeIOD_ComprehensiveSR_verify(ds, verbose, log, fix_trivials)
  File "/Users/af61/github/PyDicomVerify/rightdicom/dcmvfy/iodcomp_h.py", line 12573, in CompositeIOD_ComprehensiveSR_verify
    partial_success = Module_SRDocumentContent_verify(ds, ds, ds, verbose, log, fix_trivials)
  File "/Users/af61/github/PyDicomVerify/rightdicom/dcmvfy/module_h.py", line 73053, in Module_SRDocumentContent_verify
    partial_success =  Macro_DocumentRelationshipMacro_verify(ds, parent_ds, root_ds, verbose, log, fix_trivials)
  File "/Users/af61/github/PyDicomVerify/rightdicom/dcmvfy/module_h.py", line 72150, in Macro_DocumentRelationshipMacro_verify
    partial_success =  Macro_DocumentRelationshipMacro_verify(ds1, parent_ds1, root_ds, verbose, log, fix_trivials)
  File "/Users/af61/github/PyDicomVerify/rightdicom/dcmvfy/module_h.py", line 72150, in Macro_DocumentRelationshipMacro_verify
    partial_success =  Macro_DocumentRelationshipMacro_verify(ds1, parent_ds1, root_ds, verbose, log, fix_trivials)
  File "/Users/af61/github/PyDicomVerify/rightdicom/dcmvfy/module_h.py", line 72155, in Macro_DocumentRelationshipMacro_verify
    partial_success =  Macro_DocumentContentMacro_verify(ds1, parent_ds1, root_ds, verbose, log, fix_trivials)
  File "/Users/af61/github/PyDicomVerify/rightdicom/dcmvfy/module_h.py", line 72062, in Macro_DocumentContentMacro_verify
    partial_success =  Macro_SpatialCoordinatesMacro_verify(ds, parent_ds, root_ds, verbose, log, fix_trivials)
  File "/Users/af61/github/PyDicomVerify/rightdicom/dcmvfy/module_h.py", line 71493, in Macro_SpatialCoordinatesMacro_verify
    partial_success = verifyVM(ds["name"],
  File "/Users/af61/.pyenv/versions/pydicomverify3.8.2/lib/python3.8/site-packages/pydicom/dataset.py", line 846, in __getitem__
    tag = Tag(key)
  File "/Users/af61/.pyenv/versions/pydicomverify3.8.2/lib/python3.8/site-packages/pydicom/tag.py", line 112, in Tag
    raise ValueError("'{}' is not a valid int or DICOM keyword"
ValueError: 'name' is not a valid int or DICOM keyword
```

[prostate_sr.dcm.zip](https://github.com/ImagingDataCommons/PyDicomVerify/files/6394983/prostate_sr.dcm.zip)

**Comment by afshinmessiah** [comment]
This issue originated from automatically generated codes which I fixed in the recent commit.
